### ISSUE TITLE
输入框将password设置为1不起作用

### ISSUE THREAD

**Issue by zhaijp** [meetbill/py_menu#1]
我修改mylib中的snack_lib.py 和 snack.py 两个文件将password都设置为1 ，但是输入框还是明文显示，并没有显示*

**Comment by zhaijp** [comment]
@meetbill

**Comment by meetbill** [comment]
m.password( "label_test2", "entry_test2", "0” )
这样试试

**Comment by zhaijp** [comment]
@meetbill 
谢谢！改成你说的这种形式就ok了，这个是snack相关的api发生变化导致的吗?不知道从哪儿可以查看snack最新的api。

**Comment by meetbill** [comment]
API 没有发生改变的， m.password 是在 entry 上封装的，应该和直接用 entry 是一样的效果
